# ----------------------------------------------------
# Statistics Actor
# ----------------------------------------------------
/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save             output/stat-proton.txt

# ----------------------------------------------------
# voxellized analog actor
# ----------------------------------------------------
/gate/actor/addActor                    PromptGammaAnalogActor  anvoxel
/gate/actor/anvoxel/attachTo    	        patient
#/gate/actor/anvoxel/setInputDataFile      data/pgdb_newO500.root
/gate/actor/anvoxel/setInputDataFile      data/pgdb_newO_14e9.root
#/gate/actor/anvoxel/setInputDataFile      data/db-Oxygen.root
/gate/actor/anvoxel/save                  output/analog-O_box.mhd

#/gate/actor/anvoxel/setVoxelSize          1 1 1 mm
/gate/actor/anvoxel/setVoxelSize          2 2 2 mm

/gate/actor/anvoxel/setPosition           0 0 0 mm
/gate/actor/anvoxel/setSize               70 250 70 mm
