##World
/gate/geometry/setMaterialDatabase	data/GateMaterials.db
/gate/world/setMaterial AirO
/gate/world/geometry/setXLength 10 m
/gate/world/geometry/setYLength 10 m
/gate/world/geometry/setZLength 10 m


# Phantom
# Generate materials from Hounsfield units
# This isnt gemoetry per se, just preps stuff for the (patient) geometry
#/gate/HounsfieldMaterialGenerator/SetMaterialTable      data/Schneider2000MaterialsTable.txt
#/gate/HounsfieldMaterialGenerator/SetDensityTable       data/Schneider2000DensitiesTable.txt
#/gate/HounsfieldMaterialGenerator/SetDensityTolerance   0.05 g/cm3
#/gate/HounsfieldMaterialGenerator/SetDensityTolerance   50 g/cm3
#/gate/HounsfieldMaterialGenerator/SetOutputMaterialDatabaseFilename     data/patient-HUmaterials.db
#/gate/HounsfieldMaterialGenerator/SetOutputHUMaterialFilename           data/patient-HU2mat.txt
#/gate/HounsfieldMaterialGenerator/Generate

#/gate/world/daughters/name                         patient
#/gate/world/daughters/insert                       ImageNestedParametrisedVolume
##/gate/geometry/setMaterialDatabase              data/patient-HUmaterials.db
##/gate/patient/geometry/setHUToMaterialFile      data/patient-HU2mat.txt
#/gate/geometry/setMaterialDatabase              data/patient-HUmaterials.oxygen.db
#/gate/patient/geometry/setHUToMaterialFile      data/patient-HU2mat.oxygen.txt
##/gate/patient/geometry/setHUToMaterialFile	data/test.densityfile.txt	#just to test
#/gate/patient/geometry/setImage                 data/patient-2mm.mhd
#/gate/patient/geometry/buildAndDumpLabeledImage	output/labelimage.mhd

/gate/world/daughters/name                patient
/gate/world/daughters/insert              box
/gate/patient/geometry/setXLength         70 mm
/gate/patient/geometry/setYLength         250 mm
/gate/patient/geometry/setZLength         70 mm
/gate/patient/placement/setTranslation    0 0 0 cm
/gate/patient/setMaterial                 Oxygen
